abc_academy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('adminapp/',include('adminapp.urls')),
    path('branch/',include('branch.urls')),

    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

branch/urls.py
from django.urls import path
from . import views

app_name = 'branch'

urlpatterns = [
    path('',views.master,name="master"),
    
    path('students',views.students,name="branchstudents"),
    path('studentslist/<str:id>',views.studentslist,name="branchstudentslist"),
    path('allstudentslist',views.all_students_list,name="allbranchstudentslist"),
    path('addstudent',views.add_students_branch,name="addstudent"),
    path('editstudent/<str:id>',views.editstudent,name="editstudent"),
    path('deletestudent/<int:id>',views.delete_student,name="deletestudent"),

    path('teacherslist',views.teachers,name="teacherslist"),
    path('addteacher',views.add_teachers,name="addteacherbranch"),
    path('editteacher/<str:id>',views.editteacher,name="editteacher"),
    path('deleteteacher/<int:id>',views.delete_teacher,name="deleteteacher"),
    path('deletestudent/',views.deletestudent,name="deletestudent"),

    # path('courses',views.courses,name="courses"),
    # path('addcourses',views.add_courses,name="addcourses"),

    path('fees',views.fees,name="fees"),
    path('addfees',views.add_fees,name="addfees"),

    # Exams

    # path('examlist', views.exam_list, name="examlist"),
    # path('examaddbone', views.exam_add_b_one, name="examaddbone"),
    # path('examaddbtwo', views.exam_add_b_two, name="examaddbtwo"),
    # path('examaddbthree', views.exam_add_b_Three, name="examaddbthree"),




    # profile

    path('branchprofile',views.profile_branch, name="branchprofile"),

    path('logout_view', views.logout_view,name="logout_view"),



    path('getdata', views.getdatapayment,name="getdata"),




]

website/urls.py
from . import views
from django.urls import path

app_name ='web'

urlpatterns = [
    path('',views.homepage,name='home'),
    path('allcourse',views.allcourses,name='allcourse'),
    path('ttccourse',views.course_ttc,name='ttccourse'),
    path('fashioncourse',views.course_fashion,name='fashioncourse'),
    path('beauticiancourse',views.course_beautician,name='beauticiancourse'),
    path('onlineapplication',views.online_application,name='onlineapplication'),
    path('about',views.about_us,name='about'),
    path('contact',views.contact,name='contact'),
    path('tour',views.tourtocollege,name='tours'),
    path('blog',views.blog,name='blog'),
    path('blogpost',views.blog_post,name='blogpost'),
    path('news',views.news,name='news'),
    path('newspage',views.newspages,name='newspage'),
    path('events',views.events,name='events'),
    path('eventpage',views.eventpages,name='eventpage'),
    path('gallery',views.gallery,name='gallery'),
    path('franchise',views.franchise,name='franchise')
]

website/models.py
from django.db import models
from adminapp.models import Branch
from phone_field import PhoneField

# Create your models here.

class OnlineApplying(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()
    phone = PhoneField()
    gender = models.CharField(max_length=20)
    dob = models.DateField()
    course = models.CharField(max_length=100)
    branch = models.ForeignKey(Branch,on_delete=models.CASCADE,null=True)
    address = models.TextField()
    city = models.CharField(max_length=50,default="")
    country = models.CharField(max_length=60,default="")
    pin = models.BigIntegerField()

website/views.py
from django.shortcuts import render

from adminapp.models import Branch
from website.models import OnlineApplying

# Create your views here.

def homepage(request):
    return render(request,'website/home.html')

def allcourses(request):
    return render(request,'website/all_courses.html')

def course_ttc(request):
    return render(request,'website/ttc.html')

def course_fashion(request):
    return render(request,'website/fashion.html')

def course_beautician(request):
    return render(request,'website/beautician.html')

def online_application(request):
    branches = Branch.objects.all()
    if request.method == "POST":
        first_name = request.POST['name_apply']
        last_name = request.POST['lastname_apply']
        email = request.POST['email_apply']
        phone = request.POST['phone_apply']
        dob = request.POST['birth_apply']
        gender = request.POST['gender_apply']
        address = request.POST['address_apply']
        town = request.POST['town_apply']
        country = request.POST['country_apply']
        pin = request.POST['postal_code_apply']
        branch_apply = request.POST['branch_apply']
        course = request.POST['fav_course']

        branch = Branch.objects.get(id=branch_apply)
        new_apply = OnlineApplying(first_name=first_name,last_name=last_name,email=email,phone=phone,gender=gender,dob=dob,course=course,branch=branch,address=address,city=town,country=country,pin=pin)
        new_apply.save()
        context = {
            "status":1
        }
    context = {
        "branches":branches,
        "status":0
    }
    return render(request,'website/apply_online.html',context)

def about_us(request):
    return render(request,'website/about_us.html')

def contact(request):
    return render(request,'website/contact.html')

def tourtocollege(request):
    return render(request,'website/tour.html')

def blog(request):
    return render(request,'website/blog.html')


def blog_post(request):
    return render(request,'website/blog_post.html')

def news(request):
    return render(request,'website/news.html')

def newspages(request):
    return render(request,'website/newspage.html')

def events(request):
    return render(request,'website/events.html')

def eventpages(request):
    return render(request,'website/eventpage.html')

def gallery(request):
    return render(request,'website/gallery.html')

def franchise(request):
    return render(request,'website/franchise.html')

website/templates/website/all_courses.html
{% extends 'website/index.html' %}
{% load static %}
{% block content %}


<style>
    .row{
        height: 300px;
    }
    .img_list {
        min-height: 300px;
    }
    
    .course_list_desc {
        height:300px;
    }
    .details_list_col a.button_outline {
        margin-top: 100px;
    }
</style>


<div class="sub_header bg_1">
    <div id="intro_txt">
        <h1> <strong>ABC</strong> Training Academy courses</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, pariatur?</p>
    </div>
</div>
<!--End sub_header -->

<div id="position">
    <div class="container">
        <ul>
            <li><a href="">Home</a></li>
            <li><a href="">Category</a></li>
            <li>Page active</li>
        </ul>
    </div>
</div><!-- Position -->



<div class="container_gray_bg">
    <div class="container margin_60">
        <div class="row">
            <div class="col-md-9">

                <div class="strip_all_courses_list wow fadeIn" data-wow-delay="0.1s">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="img_list">
                                <a href="{% url 'web:ttccourse' %}"><img src="{% static 'websites/img/course_1.jpg' %}" alt="">
                                    <div class="short_info">
                                        <h3>MONTESSORI TTC</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="clearfix visible-xs-block">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="course_list_desc">
                                <h3><strong>Montessori</strong> TTC</h3>
                                <p>
                                    Montessori training is a transformative voyage that exacerbates one's wisdom and the potential of children and their ability to recast the world. Dr Maria Montessori gave special consideration to the formative psychic powers of the young child, which lead to all-around development in early childhood development (ECE and ECD).
                                </p>
                                <ul class="add_info">
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-compass"></i></span>
                                            <div class="tooltip-content">
                                                Dedicated Study Plan
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-hourglass"></i></span>
                                            <div class="tooltip-content">
                                                Admission Deadline 31/11/2015
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-medal"></i></span>
                                            <div class="tooltip-content">
                                                Most Requested Course
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-2">
                            <div class="details_list_col">
                                <div>
                                    <a href="{% url 'web:ttccourse' %}" class="button_outline">Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End strip -->


                <div class="strip_all_courses_list wow fadeIn" data-wow-delay="0.1s">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="img_list">
                                <a href="{% url 'web:fashioncourse' %}"><img src="{% static 'websites/img/course_4.jpg' %}" alt="">
                                    <div class="short_info">
                                        <h3>Fashion Designing</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="clearfix visible-xs-block">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="course_list_desc">
                                <h3><strong>Fashion Designing</strong> diploma</h3>
                                <p>
                                    Fashion Designing is one of the most prevalent design professions among students. Every year thousands of aspirants apply to various Fashion Design colleges across the country with an aspiration to become triumphant fashion designers in future. If you too are desiring a career in Fashion Design, you have anchored at the right place. 
                                </p>
                                <ul class="add_info">
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-compass"></i></span>
                                            <div class="tooltip-content">
                                                Dedicated Study Plan
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-hourglass"></i></span>
                                            <div class="tooltip-content">
                                                Admission Deadline 31/11/2015
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-medal"></i></span>
                                            <div class="tooltip-content">
                                                Most Requested Course
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-2">
                            <div class="details_list_col">
                                <div>
                                    <a href="{% url 'web:fashioncourse' %}" class="button_outline">Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End strip -->

                <div class="strip_all_courses_list wow fadeIn" data-wow-delay="0.1s">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="img_list">
                                <a href=""><img src="{% static 'websites/img/course_5.jpg' %}" alt="">
                                    <div class="short_info">
                                        <h3>BEAUTICIAN COURSE</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="clearfix visible-xs-block">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="course_list_desc">
                                <h3><strong>Beautician </strong> courses</h3>
                                <p>
                                    The Makeup industry has evolved so fast and is booming throughout the world as they are barely affected by the slump or monetary comedowns. Those who are passionate about making people pretty can build a career out of it. People want to look attractive not only to foster their self-esteem but also to introduce themselves well among their friends. This can be achievable only with the help of a skilled beautician, cosmetologist, or beauty expert. 
                                </p>
                                <ul class="add_info">
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-compass"></i></span>
                                            <div class="tooltip-content">
                                                Dedicated Study Plan
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-hourglass"></i></span>
                                            <div class="tooltip-content">
                                                Admission Deadline 31/11/2015
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tooltip_styled tooltip-effect-4">
                                            <span class="tooltip-item"><i class="pe-7s-medal"></i></span>
                                            <div class="tooltip-content">
                                                Most Requested Course
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-2">
                            <div class="details_list_col">
                                <div>
                                    <a href="{% url 'web:beauticiancourse' %}" class="button_outline">Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End strip -->

            </div>
            <!--End col-md-9 -->

            <aside class="col-md-3">
                <div class="banner">
                    <i class=" iconcustom-school"></i>
                    <h3>Take a campus tour</h3>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab quis eos, autem itaque rerum saepe!
                    </p>
                    <a href="{% url 'web:tours' %}" class="banner_bt">Start tour</a>
                </div>
                <h4><strong>How to apply</strong></h4>
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Possimus, deserunt at. Ad voluptas eveniet
                    aliquid, vero nihil natus dignissimos harum.
                </p>
                <hr class="styled">
                <div class="box_side">
                    <h5>By Phone</h5>
                    <i class="icon-phone"></i>
                    <p>
                        <a href="">(+91) – 9037304624</a><br>
                        <small>Monday to Friday 9.00am - 6.00pm</small>
                    </p>
                </div>
                <hr class="styled">
                <div class="box_side">
                    <h5>Apply Online</h5>
                    <i class="icon_desktop"></i>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi in numquam eligendi. Blanditiis
                        explicabo similique mollitia doloremque, temporibus expedita rem.
                    </p>
                    <p>
                        <a href="{% url 'web:onlineapplication' %}" class="button small">Apply online</a>
                    </p>
                </div>
            </aside>

        </div>
        <!--End row -->
    </div>
    <!--End container -->
</div>
<!--End container_gray_bg -->




{% endblock %}

website/templates/website/news.html
{% extends 'website/index.html' %}
{% load static %}
{% block content %}
 
 
<!-- SPECIFIC CSS -->
<link href="{% static 'websites/css/blog.css' %}" rel="stylesheet">


<div class="sub_header bg_1">
    <div id="intro_txt">
        <h1>ABC Academy <strong>News</strong> page</h1>
        <p>Ex saepe accusata duo, vel ne summo option delenit.</p>
    </div>
</div>
<!--End sub_header -->

<div id="position">
    <div class="container">
        <ul>
            <li><a href="">Home</a></li>
            <li><a href="">Category</a></li>
            <li>Page active</li>
        </ul>
    </div>
</div><!-- Position -->


<div class="container_gray_bg">
    <div class="container margin_60">
        <div class="row">

            <div class="col-md-9">
                <div class="post">
                    <a href="{% url 'web:newspage' %}"><img src="{% static 'websites/img/news_1_thumb.jpg' %}" alt="" class="img-responsive"></a>
                    <div class="post_info clearfix">
                        <div class="post-left">
                            <ul>
                                <li><i class="icon-calendar-empty"></i>date <em>by Mark</em></li>
                            </ul>
                        </div>
                    </div>
                    <h2>Success Stories for ABC College in 2015's</h2>
                    <p>
                        Lorem ipsum dolor sit amet, ei tincidunt persequeris efficiantur vel, usu animal patrioque omittantur et. Timeam nostrud platonem nec ea, simul nihil delectus has ex
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur qui sit reprehenderit dolorem suscipit eaque neque saepe hic, modi, iste dolore aut provident officia maiores soluta natus recusandae ipsam non id? Perferendis asperiores quisquam, soluta dolor velit hic commodi libero molestias possimus praesentium, ducimus similique maiores molestiae. Nisi, optio. Et.
                    </p>
                    <a href="{% url 'web:newspage' %}" class="button">Read more</a>
                </div><!-- end post -->


                <div class="post">
                    <a href=""><img src="{% static 'websites/img/news_1_thumb.jpg' %}" alt="" class="img-responsive"></a>
                    <div class="post_info clearfix">
                        <div class="post-left">
                            <ul>
                                <li><i class="icon-calendar-empty"></i>date <em>by Mark</em></li>
                            </ul>
                        </div>
                    </div>
                    <h2>Caps Off To Sport at Atena</h2>
                    <p>
                        Lorem ipsum dolor sit amet, ei tincidunt persequeris efficiantur vel, usu animal patrioque omittantur et. Timeam nostrud platonem nec ea, simul nihil delectus has ex
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur qui sit reprehenderit dolorem suscipit eaque neque saepe hic, modi, iste dolore aut provident officia maiores soluta natus recusandae ipsam non id? Perferendis asperiores quisquam, soluta dolor velit hic commodi libero molestias possimus praesentium, ducimus similique maiores molestiae. Nisi, optio. Et.
                    </p>
                    <a href="" class="button">Read more</a>
                </div><!-- end post -->


                <div class="post">
                    <a href=""><img src="{% static 'websites/img/blog-1.jpg' %}" alt="" class="img-responsive"></a>
                    <div class="post_info clearfix">
                        <div class="post-left">
                            <ul>
                                <li><i class="icon-calendar-empty"></i>date <em>by Mark</em></li>
                            </ul>
                        </div>
                    </div>
                    <h2>Boost in A-Level Grades in 2015 for Students</h2>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur qui sit reprehenderit dolorem suscipit eaque neque saepe hic, modi, iste dolore aut provident officia maiores soluta natus recusandae ipsam non id? Perferendis asperiores quisquam, soluta dolor velit hic commodi libero molestias possimus praesentium, ducimus similique maiores molestiae. Nisi, optio. Et.
                    </p>
                    <p>
                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Esse doloribus voluptates assumenda sapiente in sed accusamus aspernatur distinctio eveniet magnam quidem commodi, quisquam id iure labore reiciendis culpa. Ab eum deleniti nam. A nam necessitatibus hic ipsa inventore molestias, et officiis dolorum iure cum, iste dolorem. Asperiores, autem. Vitae totam voluptatibus ea, ex minus exercitationem excepturi modi iure saepe adipisci?.......
                    </p>
                    <a href="" class="button">Read more</a>
                </div><!-- end post -->

                


                <div class="text-center">
                    <ul class="pagination">
                        <li><a href="">Prev</a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="">2</a></li>
                        <li><a href="">3</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li><a href="">Next</a></li>
                    </ul><!-- end pagination-->
                </div>
            </div><!-- End col-md-8-->

            <aside class="col-md-3" id="sidebar">

                <div class="widget">
                    <div id="custom-search-input">
                        <div class="input-group col-md-12">
                            <input type="text" class="form-control input-lg" placeholder="Search" />
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-lg" type="button">
                                    <i class="icon-search-1"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div><!-- End Search -->
                <hr>
                <div class="widget">
                    <h4>Categories</h4>
                    <ul id="cat_nav">
                        <li><a href="{% url 'web:blog' %}">Blog</a></li>
                        <li><a href="{% url 'web:events' %}">Events</a></li>
                        <li><a href="{% url 'web:news' %}">News</a></li>
                    </ul>
                </div><!-- End widget -->

                <hr>
            </aside><!-- End aside -->

        </div><!-- End row-->
    </div><!-- End container -->
</div>


{% endblock %}

website/templates/website/newspage.html
{% extends 'website/index.html' %}
{% load static %}
{% block content %}

<link href="{% static 'websites/css/blog.css' %}" rel="stylesheet">


<div class="sub_header bg_1">
    <div id="intro_txt">
        <h1>ABC ACADEMY <strong>News</strong> page</h1>
        <p>Ex saepe accusata duo, vel ne summo option delenit.</p>
    </div>
</div>
<!--End sub_header -->

<div id="position">
    <div class="container">
        <ul>
            <li><a href="">Home</a></li>
            <li><a href="">Category</a></li>
            <li>Page active</li>
        </ul>
    </div>
</div><!-- Position -->


<div class="container_gray_bg">
    <div class="container margin_60">
        <div class="row">

            <div class="col-md-9">

                <div class="post">
                    <img src="{% static 'websites/img/blog-3.jpg' %}" alt="" class="img-responsive">
                    <div class="post_info clearfix">
                        <div class="post-left">
                            <ul>
                                <li><i class="icon-calendar-empty"></i>Date <em>by Mark</em></li>
                            </ul>
                        </div>
                    </div>
                    <h2>Success Stories for ABC College in 2015's.</h2>
                    <p>
                        Lorem ipsum dolor sit amet, ei tincidunt persequeris efficiantur vel, usu animal patrioque omittantur et. Timeam nostrud platonem nec ea, simul nihil delectus has ex.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur qui sit reprehenderit dolorem suscipit eaque neque saepe hic, modi, iste dolore aut provident officia maiores soluta natus recusandae ipsam non id? Perferendis asperiores quisquam, soluta dolor velit hic commodi libero molestias possimus praesentium, ducimus similique maiores molestiae. Nisi, optio. Et.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur qui sit reprehenderit dolorem suscipit eaque neque saepe hic, modi, iste dolore aut provident officia maiores soluta natus recusandae ipsam non id? Perferendis asperiores quisquam, soluta dolor velit hic commodi libero molestias possimus praesentium, ducimus similique maiores molestiae. Nisi, optio. Et.
                    </p>
                </div><!-- end post -->

            </div><!-- End col-md-8-->


            <aside class="col-md-3" id="sidebar">

                <div class="widget">
                    <div id="custom-search-input">
                        <div class="input-group col-md-12">
                            <input type="text" class="form-control input-lg" placeholder="Search" />
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-lg" type="button">
                                    <i class="icon-search-1"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div><!-- End Search -->
                <hr>
                <div class="widget">
                    <h4>Categories</h4>
                    <ul id="cat_nav">
                        <li><a href="{% url 'web:blog' %}">Blog</a></li>
                        <li><a href="{% url 'web:events' %}">Events</a></li>
                        <li><a href="{% url 'web:news' %}">News</a></li>
                    </ul>
                </div><!-- End widget -->

                <hr>

            </aside><!-- End aside -->

        </div><!-- End row-->
    </div><!-- End container -->
</div>
<!--End container_gray_bg -->


{% endblock %}