adminapp/urls.py
from django.urls import path
from . import views

app_name='admins'

urlpatterns = [
    path('', views.admindashbord, name="admindash"),
    path('branch', views.branch_list, name='branch'),

    # add branch 
    path('addbranch', views.add_branch, name="addbranch"),
    path('branchcourse/<int:id>', views.branch_course, name="branchcourse"),

    # teacher 
    path('teachers', views.teachers, name="teachers"),
    path('teachers_list/<int:id>', views.teachers_list, name="teachers_list"),
    path('add_teacher', views.add_teacher, name="addteacher"),
    path('deleteteacher/<int:id>',views.delete_teacher,name="deleteteacher"),

    # student

    path('students', views.students,name="students"),
    path('coursestudents/<int:id>',  views.students_by_courses, name="coursestudents"),
    path('studentslist', views.students_list, name="studentslist"),
    path('addstudent', views.add_student, name="addstudent"),
    path('editstudent/<int:id>', views.edit_student_by_admin, name="editstudentadmin"),
    path('studentbatchlish/<int:id>/<int:bid>', views.studentbatchlish, name="studentbatchlish"),
    # path('deletestudent/<int:id>',views.delete_student,name="deletestudent"),

    

    # courses
    path('courses',views.courses,name="courses"),
    path('addcourses',views.add_courses,name="addcourses"),
    path('editcourse/<int:id>',views.edit_course,name="editcourse"),

    # batch
    path('batch', views.batch, name="batch"),
    path('addbatch', views.add_batch, name="addbatch"),
    path('editbatch/<int:id>',views.edit_batch,name="editbatch"),
    # exams

    path('exams', views.exam, name="exams"),
    path('examsadd/<int:id>', views.exam_add_list, name="examsadd"),
    path('examsaddfirst/<int:id>', views.exam_add_first, name="examsaddfirst"),
    path('examsaddone/<str:id>', views.exam_add_one, name="examsaddone"),
    path('examsaddtwo/<str:id>', views.exam_add_two, name="examsaddtwo"),
    path('savedata/', views.savedata, name="savedata"),
    path('updateQuestion/', views.updateQuestion, name="updateQuestion"),
    path('editQuestiontdata/<int:id>',views.editQuestiontdata,name="editQuestiontdata"),
    path('editexamdata/<int:id>',views.editExam,name="editexamdata"),


    # result

    path('resultbatch', views.result_batch,name="resultbatch"),
    path('resultexam/<int:id>', views.result_exam,name="resultexam"),
    path('result/<int:id>/<int:bid>', views.result,name="result"),
    path('checkresult/<int:eid>/<int:sid>', views.checkresult,name="checkresult"),
    path('publishresult/<int:id>', views.resultPublish,name="publishresult"),

    # Exam rechedule

    path('reschedule', views.reschedule, name="reschedule"),
    path('reschedulelist/<int:id>', views.reschedule_list, name="reschedulelist"),
    path('reschedulelistdelete/<int:id>', views.delete_schedule_status, name="reschedulelistdelete"),


   # profile

   path('profile', views.admin_profile, name="adminprofile"),

    # fees admin

    path('feesadding', views.fees_adding,name="feesadding"),
    path('getdatapayment', views.getdatapayment,name="getdatapayment"),



    # login
    
    path('login', views.log_in,name="adminlogin"),
    path('logout_view', views.logout_view,name="logout_view"),
   

    # registration list

    path('checkregistration', views.check_registration,name="checkregistration"),
    path('deletereg/<int:id>',views.delete_registration,name="deletereg"),
   

]

branch/urls.py
from django.urls import path
from . import views

app_name = 'branch'

urlpatterns = [
    path('',views.master,name="master"),
    
    path('students',views.students,name="branchstudents"),
    path('studentslist/<str:id>',views.studentslist,name="branchstudentslist"),
    path('allstudentslist',views.all_students_list,name="allbranchstudentslist"),
    path('addstudent',views.add_students_branch,name="addstudent"),
    path('editstudent/<str:id>',views.editstudent,name="editstudent"),
    path('deletestudent/<int:id>',views.delete_student,name="deletestudent"),

    path('teacherslist',views.teachers,name="teacherslist"),
    path('addteacher',views.add_teachers,name="addteacherbranch"),
    path('editteacher/<str:id>',views.editteacher,name="editteacher"),
    path('deleteteacher/<int:id>',views.delete_teacher,name="deleteteacher"),
    path('deletestudent/',views.deletestudent,name="deletestudent"),

    # path('courses',views.courses,name="courses"),
    # path('addcourses',views.add_courses,name="addcourses"),

    path('fees',views.fees,name="fees"),
    path('addfees',views.add_fees,name="addfees"),

    # Exams

    # path('examlist', views.exam_list, name="examlist"),
    # path('examaddbone', views.exam_add_b_one, name="examaddbone"),
    # path('examaddbtwo', views.exam_add_b_two, name="examaddbtwo"),
    # path('examaddbthree', views.exam_add_b_Three, name="examaddbthree"),




    # profile

    path('branchprofile',views.profile_branch, name="branchprofile"),

    path('logout_view', views.logout_view,name="logout_view"),



    path('getdata', views.getdatapayment,name="getdata"),




]

student/urls.py
from . import views
from django.urls import path

app_name ='student'

urlpatterns = [
    path('',views.student_home,name='home'),
    path('profile',views.profile,name='profile'),
    path('editprofile/<int:id>',views.edit_profile,name='editprofile'),
    path('examlist',views.exam_list,name='examlist'),
    path('examinst/<int:id>',views.exam_instructions,name='examinst'),
    path('exam/<int:id>',views.exam,name='exam'),
    path('examq',views.examq,name='examq'),
    path('result',views.result,name='result'),
    path('show-result/<int:id>', views.showResult, name='showresult'),
    path('fee',views.fee,name='fee'),
    path('calendar',views.calendar,name='calendar'),                                                            
    path('questions/',views.questions,name='questions'),                                                            
    path('datasave/',views.datasave,name='datasave'),                                                            
]

teacher/urls.py
from . import views
from django.urls import path

app_name ='teacher'

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('profile',views.profile,name='profile'),
    path('editprofile/<int:id>',views.edit_profile,name='editprofile'),
    path('courses',views.courses,name='courses'),
    path('studentlist',views.studentlist,name='studentlist'),
    path('coursewisestudentlist',views.coursewise_studentlist,name='coursewisestudentlist'),
    path('result',views.result,name='result'),
    path('calander',views.calander,name='calander'),
    path('logout',views.logout,name='logout'),
]

branch/models.py
from django.db import models
from adminapp.models import Student
# Create your models here.

class Payment(models.Model):
    student = models.ForeignKey(Student,on_delete=models.PROTECT)
    paidamount = models.IntegerField(default=0)
    paiddate = models.DateField()

    class Meta:
        db_table='payment'

adminapp/views.py
from multiprocessing import context
from datetime import datetime
from pytz import timezone
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
# from abc_academy.decorators import auth_admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

from adminapp.models import Batch, Branch, Courses, Exam, Instructions, Questions, Teacher, Student
from branch.models import Payment
from django.db.models import Sum
from student.models import Answer, ExamStatus
from website.models import OnlineApplying





# Create your views here.
# @auth_admin
@login_required(login_url='/login/')
def admindashbord(request):
    students=Student.objects.all().count()
    teacher= Teacher.objects.all().count()
    branch= Branch.objects.all().count()
    course= Courses.objects.all().count()
    context={
        "is_admindash":True,
        "students":students,
        "teacher":teacher,
        "branch":branch,
        "course":course,
        
    }
    return render(request,'adminapps/home.html', context)

@login_required(login_url='/adminapp/login')
def branch_list(request):
    branches = Branch.objects.all()
    context={
        "is_branch":True,
        "branch":branches,
    }
    return render(request,'adminapps/branch.html', context)


# add branch
@login_required(login_url='/adminapp/login')
def add_branch(request):
    if Branch.objects.exists():
        branch = Branch.objects.last().id
        branch_id = 'ABC'+str(1000+branch)
    else:
        est=0
        branch_id = 'ABC'+str(1000+est)
    if request.method == 'POST':
        branch_name = request.POST['branchname']
        email = request.POST['email']
        phone = request.POST['phone']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        city = request.POST['city']
        state = request.POST['state']
        address = request.POST['address']
        district = request.POST['district']
        pincode = request.POST['pincode']
        btanch_id = branch_id

        if password == cpassword:
            new_branch = Branch(branch_id=btanch_id,branch_name=branch_name,email=email,phone_number=phone,city=city,district=district,state=state,pin=pincode,address=address,password=password)
            new_branch.save()
            User = get_user_model()
            User.objects.create_user(email=email, password=password,branch=new_branch)
            context={
                "is_addbranch":True,
                "status":1,
            }

        else:
            return HttpResponse('re enter correct password')
    else:
        context={
            "is_addbranch":True,
            "status":0
        }
    return render(request,'adminapps/addbranch.html', context)

@login_required(login_url='/adminapp/login')
def branch_course(request,id):

    context={
        "is_branch_course":True
    }
    return render(request,'adminapps/branch_course.html', context)


@login_required(login_url='/adminapp/login')
def teachers(request):
    branches = Branch.objects.all()
    context={
        "is_teachers":True,
        "branch":branches,
    }
    return render(request,'adminapps/teachers.html', context)


@login_required(login_url='/adminapp/login')
def teachers_list(request,id):
    branch = Branch.objects.get(id=id)
    teachers = Teacher.objects.filter(branch=branch)
    context={
        "is_teacherslist":True,
        "teacher":teachers,
    }
    return render(request,'adminapps/teachers_list.html', context)


@login_required(login_url='/adminapp/login')
def add_teacher(request):
    branches = Branch.objects.all()
    course=Batch.objects.all()
    if Teacher.objects.exists():
        branch = Teacher.objects.last().id
        techer_id = 'TEC'+str(1000+branch)
    else:
        est=0
        techer_id = 'TEC'+str(1000+est)
    if request.method=='POST':
        name = request.POST['name']
        gender = request.POST['gender']
        Dob = request.POST['Dob']
        mobile = request.POST['mobile']
        JoiningDate = request.POST['Joining Date']
        Qualification = request.POST['Qualification']
        Experience = request.POST['Experience']
        email = request.POST['email']
        Password = request.POST['Password']
        address = request.POST['address']
        city = request.POST['city']
        state = request.POST['state']
        zipcode = request.POST['zipcode']
        country = request.POST['country']
        techerfk= request.POST['branch']
        rpassword = request.POST['rPassword']
        batch = request.POST['course']

        branch = Branch.objects.get(id=techerfk)
        batch = Batch.objects.get(id=batch)
        if Password == rpassword:
            techer = Teacher(branch=branch,course=batch,teacher_id=techer_id,Password=Password,name=name,gender=gender,dob=Dob ,phone=mobile, email=email, joining_date=JoiningDate, qualification=Qualification, experience=Experience, address=address,pin=zipcode,country=country,state=state,city=city)
            techer.save()
            User = get_user_model()
            User.objects.create_user(email=email, password=Password,teacher=techer)
            context={
                "is_addteacher":True,
                "branch":branches,
                "course":course,
                "status":1
            }
        else:
            return HttpResponse ('Repeat correct password')
    else:
        context={
                "is_addteacher":True,
                "branch":branches,
                "course":course,
                "status":0
            }
    return render(request,'adminapps/addteacher.html', context)


@login_required(login_url='/adminapp/login')
def delete_teacher(request,id):
    Teacher.objects.get(id=id).delete()
    
    return redirect('/adminapp/teachers')



@login_required(login_url='/adminapp/login')
def students(request):
    branch= Branch.objects.all()
    context={
        "is_students":True,
        "branch":branch
    }
    return render(request,'adminapps/students.html', context)



@login_required(login_url='/adminapp/login')
def students_by_courses(request,id):
    branch = Branch.objects.get(id=id)
    course = Batch.objects.all()
    context={
        "is_students_by_courses":True,
        "course":course,
        "branch":branch,
    }
    return render(request,'adminapps/students_by_branch.html', context)



@login_required(login_url='/adminapp/login')
def studentbatchlish(request,id,bid):
    course = Batch.objects.get(id=id)
    branch = Branch.objects.get(id=bid)
    students = Student.objects.filter(course=id,branch=bid)
    context={
        "is_studentbatchlish":True,
        "students":students,
        "course":course,
        "branch":branch,
    }
    return render(request,'adminapps/students_list.html',context)

@login_required(login_url='/adminapp/login')
def students_list(request):
    
    context={
        "is_students_list":True,

    }
    return render(request,'adminapps/s_list.html', context)


@login_required(login_url='/adminapp/login')
def add_student(request):
    course= Batch.objects.all()
    branch = Branch.objects.all()
    if request.method=='POST':
        name = request.POST['name']
        lastname = request.POST['lastname']
        studentid = request.POST['studentid']
        gender = request.POST['gender']
        courseid = request.POST['course']
        dob = request.POST['dob']
        phone = request.POST['phone']
        email = request.POST['email']
        password = request.POST['password']
        fathername = request.POST['fathername']
        fatherphone = request.POST['fatherphone']
        address = request.POST['address']
        branch = request.POST['branch']
        
        course_id=Batch.objects.get(id=courseid)
        branch_id = Branch.objects.get(id=branch)
        email_exists = Student.objects.filter(email=email).exists()
        if not email_exists:
            std = Student(course=course_id,branch=branch_id,student_id=studentid, first_name=name, last_name=lastname, gender=gender, dob=dob, phone=phone,email=email ,password=password,fatherphone=fatherphone,fathername=fathername,address=address)
            std.save()
            User = get_user_model()
            User.objects.create_user(email=email, password=password,Student=std)
        else :
            # msg = "email already exists"
            context={
                "is_add_student":True,
                "course":course,
                "branch":branch,
                "status":2
            }
            return render(request,'adminapps/addstudent.html', context)
        context={
            "is_add_student":True,
            "course":course,
            "branch":branch,
            "status":1
        }
    else:
        context={
        "is_add_student":True,
        "course":course,
        "branch":branch,
        "status":0
    }
    
    return render(request,'adminapps/addstudent.html', context)


@login_required(login_url='/adminapp/login')
def edit_student_by_admin(request,id):
    print(id)
    editdetails = Student.objects.get(id=id)
    if request.method == 'POST':
        name = request.POST['name']
        lastname = request.POST['lastname']
        gender = request.POST['gender']
        phone = request.POST['phone']
        email = request.POST['email']
        # password = request.POST['password']
        fathername = request.POST['fathername']
        fatherphone = request.POST['fatherphone']
        #  email=email, password=password,
        Student.objects.filter(id=id).update(first_name=name,email=email, last_name=lastname, gender=gender,
                                             phone=phone, fatherphone=fatherphone, fathername=fathername)

adminapp/templates/adminapps/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>ABC TRAINING ACADEMY</title>
        <link rel="shortcut icon" href="{% static 'websites/logo.webp' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">
        <link rel="stylesheet" href="{% static 'webapp/plugins/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'webapp/plugins/fontawesome/css/fontawesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'webapp/plugins/fontawesome/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'webapp/plugins/datatables/datatables.min.css' %}">

    </head>
    <body>
        <div class="main-wrapper">
            <div class="header">
                <div class="header-left">
                    <a href="#" class="logo">
                        <img src="{% static 'websites/logo.webp' %}" alt="Logo">
                    </a>
                    <a href="#" class="logo logo-small">
                        <img src="{% static 'websites/logo.webp' %}" alt="Logo" width="30" height="30">
                    </a>
                </div>
                <a href="javascript:void(0);" id="toggle_btn">
                    <i class="fas fa-align-left"></i>
                </a>
                <!-- <div class="top-nav-search">
                    <form>
                        <input type="text" class="form-control" placeholder="Search here">
                        <button class="btn" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div> -->
                <a class="mobile_btn" id="mobile_btn">
                    <i class="fas fa-bars"></i>
                </a>
                <ul class="nav user-menu">
                   
                    <li class="nav-item dropdown has-arrow">
                        <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                            <span class="user-img">
                                <img class="rounded-circle"
                                     src="{% static 'default.jpg' %}"
                                     width="31"
                                     alt="admin">
                            </span>
                            <span>Admin</span>
                        </a>
                        <div class="dropdown-menu">
                            <div class="user-header">
                                <div class="avatar avatar-sm">
                                    <img src="{% static 'default.jpg' %}"
                                         alt="User Image"
                                         class="avatar-img rounded-circle">
                                </div>
                                <div class="user-text">
                                    <h6>Admin</h6>
                                    <p class="text-muted mb-0">
                                        Administrator
                                    </p>
                                </div>
                            </div>
                            <!-- <a class="dropdown-item" href="{% url 'admins:adminprofile' %}">My Profile</a> -->
                            
                            <a class="dropdown-item" href="{% url 'admins:logout_view' %}">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
                    <div id="sidebar-menu" class="sidebar-menu">
                        <ul>
                            <li class="menu-title">
                                <span>Main Menu</span>
                            </li>
                            <li {% if is_admindash %} class="active"{% endif %}>
                                <a href="{% url 'admins:admindash' %}"><i class="fas fa-user-graduate"></i> <span>Dashboard</span></span></a>
                            </li>
                            <li class="submenu">
                                <a href=""><i class="fas fa-building"></i> <span> Branch</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li {% if is_branch %} class="active"{% endif %}>
                                        <a href="{% url 'admins:branch' %}">Branch List</a>
                                    </li>
                                    <li {% if is_addbranch %} class="active"{% endif %}>
                                        <a href="{% url 'admins:addbranch' %}">Add Branch</a>
                                    </li>
                                </ul>
                            </li>
                            <li {% if is_teachers %} class="active submenu"
                                {% elif is_teacherslist %} class="active submenu"
                                {% elif is_addteacher %} class="active submenu"
                                {% endif %}>
                                <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Teachers</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li {% if is_teachers %} class="active"{% endif %} 
                                        {% if is_teacherslist %} class="active"{% endif %}>
                                        <a href="{% url 'admins:teachers' %}">Teacher List</a>
                                    </li>
                                    <!-- <li>
                                        <a href="teacher-details.html">Teacher View</a>
                                    </li> -->
                                    <li {% if is_addteacher %} class="active"{% endif %}>
                                        <a href="{% url 'admins:addteacher' %}">Teacher Add</a>
                                    </li>
                                    <!-- <li>
                                        <a href="edit-teacher.html">Teacher Edit</a>
                                    </li> -->
                                </ul>
                            </li>
                            <li {% if is_students %} class="active submenu"
                                {% elif is_students_by_courses %} class="active submenu"
                                {% elif is_students_list %} class="active submenu"
                                {% elif is_add_student %} class="active submenu"
                                {% elif is_studentbatchlish %} class="active submenu"
                                {% elif is_edit_student_by_admin %} class="active submenu"
                                {% endif %}>
                                <a href="#"><i class="fas fa-user-graduate"></i> <span> Students</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li {% if is_students %} class="active"{% endif %}
                                        {% if is_students_by_courses %} class="active"{% endif %}
                                        {% if is_students_list %} class="active"{% endif %}>
                                        <a href="{% url 'admins:students' %}">Student List</a>
                                    </li>
                                    <li {% if is_add_student %} class="active"{% endif %}>
                                        <a href="{% url 'admins:addstudent' %}">Student Add</a>
                                    </li>
                                   
                                    
                                </ul>
                            </li>
                           
                            <li {% if is_courses %} class="active"{% endif %} {% if is_add_courses %} class="active"{% endif %}>
                                <a href="{% url 'admins:courses' %}"><i class="fa fa-book"></i> <span>Courses</span></a>
                            </li>
                            <li {% if is_batch %} class="active"{% endif %}>
                                <a href="{% url 'admins:batch' %}"><i class="fa fa-users"></i> <span>Batches</span></a>
                            </li>
                            <li {% if is_exam %} class="active"{% endif %}
                                {% if is_exam_add_list %} class="active"{% endif %}
                                {% if is_exam_add_first %} class="active"{% endif %}
                                {% if is_editExam %} class="active"{% endif %}
                                {% if is_exam_add_two %} class="active"{% endif %}>
                                <a href="{% url 'admins:exams' %}"><i class="fas fa-clipboard-list"></i> <span>Exam </span></a>
                            </li>
                            <li {% if is_result_batch %} class="active"{% endif %}
                                {% if is_result_exam %} class="active"{% endif %}
                                {% if is_result %} class="active"{% endif %}
                                {% if is_checkresult %} class="active"{% endif %}>
                                <a href="{% url 'admins:resultbatch' %}"><i class="fas fa-clipboard"></i><span>Result</span></a>
                            </li>
                            <li {% if is_reschedule %} class="active"{% endif %}>
                                <a href="{% url 'admins:reschedule' %}"><i class="fas fa-undo"></i><span>Reschedule</span></a>
                            </li>
                            <li class="menu-title">
                                <span>Management</span>         
                            </li>
                            
                            <li {% if is_fees_adding %} class="active"{% endif %}>
                                <a href="{% url 'admins:feesadding' %}"><i class="fas fa-comment-dollar"></i> <span>Fees</span></a>
                            </li>
                            <li {% if is_check_registration %} class="active"{% endif %}>
                                <a href="{% url 'admins:checkregistration' %}"><i class="fas fa-list"></i> <span>Registrations</span></a>
                            </li>
                            
                           
                        </ul>
                    </div>
                </div>
            </div>
            
        {% block content  %}
        {% endblock  %}
        </div>
        {% block js %}
        {% endblock  %}
        <script src="{% static 'webapp/js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/apexchart/apexcharts.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/apexchart/chart-data.js' %}"></script>
        <script src="{% static 'webapp/js/script.js' %}"></script>

    
        
        <!-- <script src="{% static 'webapp/plugins/datatables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/datatables/datatables.min.js' %}"></script> -->

        <!-- <script>
            if ($('.datatable').length > 0) {
		    $('.datatable').DataTable({
			language: {
				search: '<i class="fas fa-search"></i>',
				searchPlaceholder: "Search"
			  }
		});
	}
        </script> -->
        
    </body>
</html>

adminapp/templates/adminapps/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Preskool - Login</title>
        <link rel="shortcut icon" href="{% static 'websites/logo.webp' %}">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">
        <link rel="stylesheet"
              href="{% static 'webapp/plugins/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet"
              href="{% static 'webapp/plugins/fontawesome/css/fontawesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'webapp/plugins/fontawesome/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">
    </head>
    <body>
        <div class="main-wrapper login-body">
            <div class="login-wrapper">
                <div class="container">
                    <div class="loginbox">
                        <div class="login-left">
                            <img class="img-fluid" src="{% static 'websites/logo.webp' %}" alt="Logo">
                        </div>
                        <div class="login-right">
                            <div class="login-right-wrap">
                                <h1>Login</h1>
                                <p class="account-subtitle">
                                    Access to our dashboard
                                </p>
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input class="form-control" type="text" placeholder="Email" name="email">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" type="text" placeholder="Password" name="password">
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary btn-block" type="submit">Login</button>
                                    </div>
                                </form>
                                <div class="text-center forgotpass">
                                    <p style="color: red;"> {{msg}}</p>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'webapp/js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'webapp/js/script.js' %}"></script>
    </body>
</html>