abc_academy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('adminapp/',include('adminapp.urls')),
    path('branch/',include('branch.urls')),

    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from . import views

app_name='admins'

urlpatterns = [
    path('', views.admindashbord, name="admindash"),
    path('branch', views.branch_list, name='branch'),

    # add branch 
    path('addbranch', views.add_branch, name="addbranch"),
    path('branchcourse/<int:id>', views.branch_course, name="branchcourse"),

    # teacher 
    path('teachers', views.teachers, name="teachers"),
    path('teachers_list/<int:id>', views.teachers_list, name="teachers_list"),
    path('add_teacher', views.add_teacher, name="addteacher"),
    path('deleteteacher/<int:id>',views.delete_teacher,name="deleteteacher"),

    # student

    path('students', views.students,name="students"),
    path('coursestudents/<int:id>',  views.students_by_courses, name="coursestudents"),
    path('studentslist', views.students_list, name="studentslist"),
    path('addstudent', views.add_student, name="addstudent"),
    path('editstudent/<int:id>', views.edit_student_by_admin, name="editstudentadmin"),
    path('studentbatchlish/<int:id>/<int:bid>', views.studentbatchlish, name="studentbatchlish"),
    # path('deletestudent/<int:id>',views.delete_student,name="deletestudent"),

    

    # courses
    path('courses',views.courses,name="courses"),
    path('addcourses',views.add_courses,name="addcourses"),
    path('editcourse/<int:id>',views.edit_course,name="editcourse"),

    # batch
    path('batch', views.batch, name="batch"),
    path('addbatch', views.add_batch, name="addbatch"),
    path('editbatch/<int:id>',views.edit_batch,name="editbatch"),
    # exams

    path('exams', views.exam, name="exams"),
    path('examsadd/<int:id>', views.exam_add_list, name="examsadd"),
    path('examsaddfirst/<int:id>', views.exam_add_first, name="examsaddfirst"),
    path('examsaddone/<str:id>', views.exam_add_one, name="examsaddone"),
    path('examsaddtwo/<str:id>', views.exam_add_two, name="examsaddtwo"),
    path('savedata/', views.savedata, name="savedata"),
    path('updateQuestion/', views.updateQuestion, name="updateQuestion"),
    path('editQuestiontdata/<int:id>',views.editQuestiontdata,name="editQuestiontdata"),
    path('editexamdata/<int:id>',views.editExam,name="editexamdata"),


    # result

    path('resultbatch', views.result_batch,name="resultbatch"),
    path('resultexam/<int:id>', views.result_exam,name="resultexam"),
    path('result/<int:id>/<int:bid>', views.result,name="result"),
    path('checkresult/<int:eid>/<int:sid>', views.checkresult,name="checkresult"),
    path('publishresult/<int:id>', views.resultPublish,name="publishresult"),

    # Exam rechedule

    path('reschedule', views.reschedule, name="reschedule"),
    path('reschedulelist/<int:id>', views.reschedule_list, name="reschedulelist"),
    path('reschedulelistdelete/<int:id>', views.delete_schedule_status, name="reschedulelistdelete"),


   # profile

   path('profile', views.admin_profile, name="adminprofile"),

    # fees admin

    path('feesadding', views.fees_adding,name="feesadding"),
    path('getdatapayment', views.getdatapayment,name="getdatapayment"),



    # login
    
    path('login', views.log_in,name="adminlogin"),
    path('logout_view', views.logout_view,name="logout_view"),
   

    # registration list

    path('checkregistration', views.check_registration,name="checkregistration"),
    path('deletereg/<int:id>',views.delete_registration,name="deletereg"),
   

]

branch/urls.py
from django.urls import path
from . import views

app_name = 'branch'

urlpatterns = [
    path('',views.master,name="master"),
    
    path('students',views.students,name="branchstudents"),
    path('studentslist/<str:id>',views.studentslist,name="branchstudentslist"),
    path('allstudentslist',views.all_students_list,name="allbranchstudentslist"),
    path('addstudent',views.add_students_branch,name="addstudent"),
    path('editstudent/<str:id>',views.editstudent,name="editstudent"),
    path('deletestudent/<int:id>',views.delete_student,name="deletestudent"),

    path('teacherslist',views.teachers,name="teacherslist"),
    path('addteacher',views.add_teachers,name="addteacherbranch"),
    path('editteacher/<str:id>',views.editteacher,name="editteacher"),
    path('deleteteacher/<int:id>',views.delete_teacher,name="deleteteacher"),
    path('deletestudent/',views.deletestudent,name="deletestudent"),

    # path('courses',views.courses,name="courses"),
    # path('addcourses',views.add_courses,name="addcourses"),

    path('fees',views.fees,name="fees"),
    path('addfees',views.add_fees,name="addfees"),

    # Exams

    # path('examlist', views.exam_list, name="examlist"),
    # path('examaddbone', views.exam_add_b_one, name="examaddbone"),
    # path('examaddbtwo', views.exam_add_b_two, name="examaddbtwo"),
    # path('examaddbthree', views.exam_add_b_Three, name="examaddbthree"),




    # profile

    path('branchprofile',views.profile_branch, name="branchprofile"),

    path('logout_view', views.logout_view,name="logout_view"),



    path('getdata', views.getdatapayment,name="getdata"),




]

student/urls.py
from . import views
from django.urls import path

app_name ='student'

urlpatterns = [
    path('',views.student_home,name='home'),
    path('profile',views.profile,name='profile'),
    path('editprofile/<int:id>',views.edit_profile,name='editprofile'),
    path('examlist',views.exam_list,name='examlist'),
    path('examinst/<int:id>',views.exam_instructions,name='examinst'),
    path('exam/<int:id>',views.exam,name='exam'),
    path('examq',views.examq,name='examq'),
    path('result',views.result,name='result'),
    path('show-result/<int:id>', views.showResult, name='showresult'),
    path('fee',views.fee,name='fee'),
    path('calendar',views.calendar,name='calendar'),                                                            
    path('questions/',views.questions,name='questions'),                                                            
    path('datasave/',views.datasave,name='datasave'),                                                            
]

student/models.py
from django.db import models
import datetime

from adminapp.models import Exam, Student,Questions

# Create your models here.

class ExamStatus(models.Model):
    # status_choices = (('Attended','Attended'),('Not Attended','Not Attended'))
    exam_id = models.ForeignKey(Exam,on_delete=models.CASCADE)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    status = models.CharField(max_length=30)
    Attended_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('exam_id', 'student')

class Answer(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE,null=True)
    exam = models.ForeignKey(Exam,on_delete=models.CASCADE,null=True)
    question = models.ForeignKey(Questions,on_delete=models.CASCADE,null=True)
    savedaswer=models.CharField(max_length=30000)
    ans_true = models.BooleanField(default=False)
    mark = models.FloatField(default=0)
    status=models.CharField(max_length=30,null=True)

student/views.py
from datetime import datetime, timedelta, time
# from operator import le

from django.http import JsonResponse

from adminapp.models import Exam, Instructions, Questions, Student,Batch
from django.shortcuts import redirect, render

from django.contrib.auth import get_user_model

from django.contrib.auth.decorators import login_required
from branch.models import Payment

# from branch.models import Payment
from django.db.models import Sum

from student.models import Answer, ExamStatus
from datetime import datetime
from pytz import timezone 
import time

# Create your views here.
@login_required(login_url='/adminapp/login')
def student_home(request):
    student=request.user.Student
    exams = Exam.objects.filter(batch=student.course).count()
   
    context = {
        "is_home": True,
        "stexamcountudent":student,
        "examcount":exams,
        "student":student
        }
    return render(request,'student/student_home.html',context)


@login_required(login_url='/adminapp/login')
def profile(request):
    student=request.user.Student
    student_profile=Student.objects.get(id=request.user.Student.id)
    context = {
        "is_profile": True,
        "student":student,
        "student_profile":student_profile,
        }
    return render(request,'student/profile.html',context)


@login_required(login_url='/adminapp/login')
def edit_profile(request,id):
    student=request.user.Student
    students_id = student.id
    if request.method == "POST":
        if 'fname' in request.POST:
            # sid=request.POST['sid']
            first_name=request.POST['fname']
            second_name=request.POST['sname']
            # gender=request.POST['gender']
            # dob=request.POST['dob']
            # email=request.POST['email']
            phone=request.POST['phone']
            Student.objects.filter(id=id).update(first_name=first_name,last_name=second_name,phone=phone)
            return redirect('student:profile')
        elif 'address' in request.POST:
            address=request.POST['address']
            Student.objects.filter(id=students_id).update(address=address)
            return redirect('student:profile')
        elif 'currentpassword' in request.POST:
            currentpassword=request.POST['currentpassword']
            newpassword=request.POST['newpassword']
            cnewpassword=request.POST['cnewpassword']
            oldpassword =  Student.objects.get(id=students_id).password
            if newpassword == cnewpassword:
                
                if oldpassword == currentpassword:
                    Student.objects.filter(id=students_id).update(password=newpassword)
                    changePassword = get_user_model().objects.get(id=request.user.id)
                    changePassword.set_password(newpassword)
                    changePassword.save()
                    return redirect('student:profile')
                else:
                    msg = "Incorrect old password"
            else:
                msg = "re enter correct password"
         
    edit_profile=Student.objects.get(id=id)
    context = {
        "is_editprofile": True,
        "edit_profile":edit_profile,
        "student":student
        }
    return render(request,'student/edit_profile.html',context)


@login_required(login_url='/adminapp/login')
def exam_list(request):
    student = request.user.Student
    exam = Exam.objects.filter(batch=student.course)
    context = {
        "is_examlist": True,
        "student":student,
        "exam":exam,
        }
    return render(request,'student/exam_list.html',context)



@login_required(login_url='/adminapp/login')
def exam_instructions(request,id):
    context = {}
    now = datetime.now(timezone("Asia/Kolkata")).strftime('%Y-%m-%d')
    exam = Exam.objects.get(id=id)
    exam_date = exam.exam_date
    exam_time = exam.start_time
    end_time = exam.end_time
   
    if str(exam_date) == str(now):
        currentTime =  datetime.now().time()
        if currentTime > exam_time and currentTime < end_time:   
            pass
        else:
            return redirect('/student/examlist')  
    else:
           
        return redirect('/student/examlist')
    if Instructions.objects.filter(exam_id=exam).exists():
        instructions = Instructions.objects.get(exam_id=exam)
        context = {
            "is_examinst": True,
            "instructions":instructions,
            "exam":exam
        }
    else:
         context = {
            "is_examinst": True,
            "instructions":None,
            "exam":exam
        }
    return render(request,'student/exam_instructions.html',context)


@login_required(login_url='/adminapp/login')
def exam(request,id):
    if ExamStatus.objects.filter(student=request.user.Student,exam_id__id=id).exists():
        return redirect('/student/examlist')    
    exam = Exam.objects.get(id=id)
    student = request.user.Student
    status = "Attended"
    # today = datetime.now().date()
    # attnd_time = datetime.combine(today, time())
    Attending_obj = ExamStatus(exam_id=exam,student=student,status=status)
    Attending_obj.save()
    que = Questions.objects.filter(exam_id=exam)
    context = {
        "is_exam": True,
        "exam":exam,
        "que":que
        }
    return render(request,'student/exam.html',context)


@login_required(login_url='/adminapp/login')
def examq(request):
    student=request.user.Student
    context = {
        "is_exam": True,
        "student":student,
        }
    return render(request,'student/examq.html',context)

def result(request):
    student=request.user.Student
    exam = Exam.objects.filter(batch=student.course,is_published=True)
    context = {
        "is_result": True,
        "student":student,
        "exam":exam,
        }
    return render(request,'student/result.html',context)


def showResult(request,id):
    student=request.user.Student
    answer = Answer.objects.filter(exam=id,student=student)
    total_mark = Questions.objects.filter(exam_id=id).aggregate(Sum('mark'))
    mark = Answer.objects.filter(exam=id,student=student).aggregate(Sum('mark'))
    std= Student.objects.get(id=student.id)
    context = {
        "is_result": True,
        "answer":answer,
        "std":student,
        "total_mark":total_mark,
        "mark":mark,
        }
    return render(request,'student/show-result.html',context)

@login_required(login_url='/adminapp/login')
def fee(request):
    id=request.user.Student.id
    student = request.user.Student
    paymentdetails = Payment.objects.filter(student=request.user.Student)
    viewpro=Student.objects.get(id=id) 
    total=viewpro.course.course.total_fees
    balanceamount=total
    recvamount = ""
    if paymentdetails.exists():
        recivedamount = Payment.objects.filter(student=viewpro.id).aggregate(Sum('paidamount'))
        recvamount = recivedamount['paidamount__sum']
        balanceamount  = total - recivedamount['paidamount__sum']
       

    context = {
        "is_fee": True,
        "paymentdetails":paymentdetails,
        "recvamount":recvamount,
        "balanceamount":balanceamount,
        "total":total,
        "student":student,

        }
    return render(request,'student/fee.html',context)



def calendar(request):
    context = {
        "is_calendar": True,
        }
    return render(request,'student/calendar.html',context)


@login_required(login_url='/adminapp/login')
def questions(request):
    if request.method == "POST":
        examId = request.POST['exam_id']
        examIds = []
        countQt =  Questions.objects.filter(exam_id = examId).count()
        qts = Questions.objects.filter(exam_id = examId)
        attendedQt = Answer.objects.filter(exam= examId,student=request.user.Student).count()
        for i in qts:
            if Answer.objects.filter(question=i.id,student=request.user.Student).exists():
                pass
            else:
                examIds.append(i.id)
        question = Questions.objects.filter(id__in= examIds).first()
        if len(examIds) > 0:
            choices = question.option.split(',')
            data={
                "question":question.question,
                "id":question.id,
                "option":choices,
                'total_questions':countQt,
                "type":question.type,
                "lenght":len(examIds),
                "attended_questions":attendedQt,
                "mark":question.mark,
            }
        else:
             data={
                "lenght":0,
            }
        return JsonResponse(data)
        
        

def datasave(request):
    if request.method =='POST':
        questionid=request.POST['questionId']
        answer=request.POST['answer']
        exam=request.POST['exam_id']
        studentid=request.user.Student
        queid= Questions.objects.get(id=questionid)
        mark = queid.mark
        examid= Exam.objects.get(id=exam)
        if queid.true_answer == answer:
            ans=Answer(exam=examid,student=studentid,question=queid,savedaswer=answer,ans_true=True,mark=mark,status="Wait For Valuation" )
            ans.save()
        else :
            ans=Answer(exam=examid,student=studentid,question=queid,savedaswer=answer,status="Wait For Valuation" )
            ans.save()
        return JsonResponse({'msg':'added'})

student/templates/student/exam_list.html
{% extends 'student/master.html' %}
{% load static %}
{% block content %}


<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-6">
                    <h3 class="page-title">Exams</h3>
                    <ul class="breadcrumb">
                        <li class=""><a href="{% url 'student:home' %}">Dashboard /</a></li>
                        <li class="breadcrumb-item active">Exams</li>
                    </ul>
                </div>
            </div>
        </div>



        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-center table-hover datatable">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Exam/Subject</th>
                                        <th>Date</th>
                                        <th>Start Time</th>
                                        <th>End Time</th>
                                        <th>Total Hours</th>
                                        <!-- <th>Status</th> -->
                                        <th class="text-start">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in exam %}
                                        <tr>
                                            <td>
                                                <h2>
                                                    <a href="">{{i.exam_name}} </a>
                                                </h2>
                                            </td>
                                            <td><b>
                                                {{i.exam_date}}</b>
                                            </td>
                                            <td>{{i.start_time}}</td>
                                            <td>{{i.end_time}}</td>
                                            <td><b>{{i.duration}} MINUTES</b></td>
                                            <!-- <td><span class="badge badge-pill bg-warning-light">Not Attended</span></td> -->
                                            <td class="text-start">
                                                <a href="{% url 'student:examinst' i.id %}"
                                                    class="btn btn-sm btn-white text-primary me-2"><i
                                                        class="far fa-edit me-1"></i> Attend Exam</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

student/templates/student/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ABC TRAINING ACADEMY</title>

    <link rel="shortcut icon" href="{% static 'websites/logo.webp' %}">

    <link rel="stylesheet" href="{% static 'teacher/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'teacher/plugins/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'teacher/plugins/fontawesome/css/all.min.css' %}">

    <!-- Google material CDN -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'teacher/css/style.css' %}">

</head>

<body class="nk-body bg-lighter npc-default has-sidebar no-touch nk-nio-theme">

    <!-- Header================================================== -->
    <div class="main-wrapper">
        <div class="header header-one">

            <div class="header-left header-left-one">
                <a href="" class="logo">
                    <img src="{% static 'websites/logo.webp' %}" alt="Logo">
                </a>
                <a href="" class="white-logo">
                    <img src="{% static 'websites/logo.webp' %}" alt="Logo">
                </a>
                <a href="" class="logo logo-small">
                    <img src="{% static 'websites/logo.webp' %}" alt="Logo" width="30" height="30">
                </a>
            </div>


            <a href="javascript:void(0);" id="toggle_btn">
                <i class="fas fa-bars"></i>
            </a>



            <a class="mobile_btn" id="mobile_btn">
                <i class="fas fa-bars"></i>
            </a>


            <ul class="nav nav-tabs user-menu">

               

                <li class="nav-item dropdown has-arrow main-drop">
                    <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                        <span class="user-img">
                            <img src="{% static 'default.jpg' %}" alt="">
                            <span class="status online"></span>
                        </span>
                        <span>{{student.first_name|upper}} {{student.last_name|upper}}</span>
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'student:profile' %}"><i class="fa fa-user" class="me-1"></i>&nbsp;
                                      Profile</a>
                     
                        <a class="dropdown-item" href="{% url 'admins:logout_view' %}"><i class="fa fa-sign-out-alt" class="me-1"></i>&nbsp;
                            Logout</a>
                    </div>
                </li>

            </ul>

        </div>
        


        <div class="sidebar" id="sidebar">
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                        <!-- <li class="menu-title"><span>Main</span></li> -->
                        <li {% if is_home %} class="active"{% endif %}>
                            <a href="{% url 'student:home' %}"><i class="fa fa-th"></i> <span>Dashboard</span></a>
                        </li>
                        <!-- <li class="" {% if is_profile %} class="active" {% elif is_editprofile %} class="active" {% endif %}>
                            <a href=""><i class="fa fa-address-card"></i> <span>My Profile</span> 
                            <ul>
                                <li {% if is_profile %} class="active" {% endif %}><a href="{% url 'student:profile' %}">My Profile</a></li>
                                
                            </ul>
                        </li> -->
                        <li {% if is_profile %} class="active" {% endif %}><a href="{% url 'student:profile' %}">
                            <i class="fa fa-address-card"></i> <span>My Profile</span></a></li>
                        <li {% if is_examlist %} class="active" {% elif is_examinst %} class="active" {% elif is_exam %} class="active" {% endif %}>
                            <a href="{% url 'student:examlist' %}"><i class="fa fa-edit"></i> <span>Exam</span></a>
                        </li>
                        <li {% if is_result %} class="active" {% endif %}>
                            <a href="{% url 'student:result' %}"><i class="fa fa-clipboard"></i> <span>Result</span></a>
                        </li> 
                        <li {% if is_fee %} class="active" {% endif %}>
                            <a href="{% url 'student:fee' %}"><i class="fas fa-rupee-sign"></i> <span>Fee</span></a>
                        </li>
                        <!-- <li {% if is_calendar %} class="active" {% endif %}>
                            <a href="{% url 'student:calendar' %}"><i class="fa fa-calendar"></i> <span>Calendar</span></a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </div>


        {% block content %}


        {% endblock %}

    </div>


<!-- Common JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'teacher/js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'teacher/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'teacher/js/feather.min.js' %}"></script>
<script src="{% static 'teacher/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'teacher/plugins/apexchart/apexcharts.min.js' %}"></script>
<script src="{% static 'teacher/plugins/apexchart/chart-data.js' %}"></script>

<!-- datepicker JS -->
<script src="{% static 'teacher/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'teacher/js/bootstrap-datetimepicker.min.js' %}"></script>

<!-- calender JS -->
<script src="{% static 'teacher/js/jquery-ui.min.js' %} "></script>
<script src="{% static 'teacher/plugins/fullcalendar/fullcalendar.min.js' %}"></script>
<script src="{% static 'teacher/plugins/fullcalendar/jquery.fullcalendar.js' %}"></script>

<!-- DataTable JS -->
<script src="{% static 'teacher/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'teacher/plugins/datatables/datatables.min.js' %} "></script>

<!-- counter JS -->
<script src="{% static 'teacher/plugins/countup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'teacher/plugins/countup/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'teacher/plugins/countup/jquery.missofis-countdown.js' %}"></script>

<script>
   
    
    // datatable
    if ($('.datatable').length > 0) {
        $('.datatable').DataTable({
            language: {
                search: '<i class="fas fa-search"></i>',
                searchPlaceholder: "Search"
            }
        });
    }
    // end datatable


    if ($('.datetimepicker').length > 0) {
        $('.datetimepicker').datetimepicker({
            format: 'DD-MM-YYYY',
            icons: {
                up: "fas fa-angle-up",
                down: "fas fa-angle-down",
                next: 'fas fa-angle-right',
                previous: 'fas fa-angle-left'
            }
        });
    }

    //    toggle
    $(document).on('click', '#toggle_btn', function () {
        if ($('body').hasClass('mini-sidebar')) {
            $('body').removeClass('mini-sidebar');
            $('.subdrop + ul').slideDown();
        } else {
            $('body').addClass('mini-sidebar');
            $('.subdrop + ul').slideUp();
        }
        setTimeout(function () {
            mA.redraw();
            mL.redraw();
        }, 300);
        return false;
    });


    // filters
    $(document).on('click', '#filter_search', function () {
        $('#filter_inputs').show();
    });

    // selectbox
    $('.app-listing .selectBox').on("click", function () {
        $(this).parent().find('#checkBoxes').fadeToggle();
        $(this).parent().parent().siblings().find('#checkBoxes').fadeOut();
    });

    $('.invoices-main-form .selectBox').on("click", function () {
        $(this).parent().find('#checkBoxes-one').fadeToggle();
        $(this).parent().parent().siblings().find('#checkBoxes-one').fadeOut();
    });
    

    // Variables declarations

    var $wrapper = $('.main-wrapper');
    var $pageWrapper = $('.page-wrapper');
    var $slimScrolls = $('.slimscroll');

    // Sidebar
    var Sidemenu = function () {
        this.$menuItem = $('#sidebar-menu a');
    };

    function init() {
        var $this = Sidemenu;
        $('#sidebar-menu a').on('click', function (e) {
            if ($(this).parent().hasClass('submenu')) {
                e.preventDefault();
            }
            if (!$(this).hasClass('subdrop')) {
                $('ul', $(this).parents('ul:first')).slideUp(350);
                $('a', $(this).parents('ul:first')).removeClass('subdrop');
                $(this).next('ul').slideDown(350);
                $(this).addClass('subdrop');
            } else if ($(this).hasClass('subdrop')) {
                $(this).removeClass('subdrop');
                $(this).next('ul').slideUp(350);
            }
        });
        $('#sidebar-menu ul li.submenu a.active').parents('li:last').children('a:first').addClass('active').trigger('click');
    }

    // Sidebar Initiate
    init();

    // Mobile menu sidebar overlay
    $('body').append('<div class="sidebar-overlay"></div>');
    $(document).on('click', '#mobile_btn', function () {
        $wrapper.toggleClass('slide-nav');
        $('.sidebar-overlay').toggleClass('opened');
        $('html').toggleClass('menu-opened');
        return false;
    });

    // Sidebar overlay
    $(".sidebar-overlay").on("click", function () {
        $wrapper.removeClass('slide-nav');
        $(".sidebar-overlay").removeClass("opened");
        $('html').removeClass('menu-opened');
    });

    // Page Content Height
    if ($('.page-wrapper').length > 0) {
        var height = $(window).height();
        $(".page-wrapper").css("min-height", height);
    }

    // Page Content Height Resize
    $(window).resize(function () {
        if ($('.page-wrapper').length > 0) {
            var height = $(window).height();
            $(".page-wrapper").css("min-height", height);
        }
    });

    // Select 2
    if ($('.select').length > 0) {
        $('.select').select2({
            minimumResultsForSearch: -1,
            width: '100%'
        });
    }


</script>


</body>

</html>