abc_academy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('adminapp/',include('adminapp.urls')),
    path('branch/',include('branch.urls')),

    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

branch/urls.py
from django.urls import path
from . import views

app_name = 'branch'

urlpatterns = [
    path('',views.master,name="master"),
    
    path('students',views.students,name="branchstudents"),
    path('studentslist/<str:id>',views.studentslist,name="branchstudentslist"),
    path('allstudentslist',views.all_students_list,name="allbranchstudentslist"),
    path('addstudent',views.add_students_branch,name="addstudent"),
    path('editstudent/<str:id>',views.editstudent,name="editstudent"),
    path('deletestudent/<int:id>',views.delete_student,name="deletestudent"),

    path('teacherslist',views.teachers,name="teacherslist"),
    path('addteacher',views.add_teachers,name="addteacherbranch"),
    path('editteacher/<str:id>',views.editteacher,name="editteacher"),
    path('deleteteacher/<int:id>',views.delete_teacher,name="deleteteacher"),
    path('deletestudent/',views.deletestudent,name="deletestudent"),

    # path('courses',views.courses,name="courses"),
    # path('addcourses',views.add_courses,name="addcourses"),

    path('fees',views.fees,name="fees"),
    path('addfees',views.add_fees,name="addfees"),

    # Exams

    # path('examlist', views.exam_list, name="examlist"),
    # path('examaddbone', views.exam_add_b_one, name="examaddbone"),
    # path('examaddbtwo', views.exam_add_b_two, name="examaddbtwo"),
    # path('examaddbthree', views.exam_add_b_Three, name="examaddbthree"),




    # profile

    path('branchprofile',views.profile_branch, name="branchprofile"),

    path('logout_view', views.logout_view,name="logout_view"),



    path('getdata', views.getdatapayment,name="getdata"),




]

student/urls.py
from . import views
from django.urls import path

app_name ='student'

urlpatterns = [
    path('',views.student_home,name='home'),
    path('profile',views.profile,name='profile'),
    path('editprofile/<int:id>',views.edit_profile,name='editprofile'),
    path('examlist',views.exam_list,name='examlist'),
    path('examinst/<int:id>',views.exam_instructions,name='examinst'),
    path('exam/<int:id>',views.exam,name='exam'),
    path('examq',views.examq,name='examq'),
    path('result',views.result,name='result'),
    path('show-result/<int:id>', views.showResult, name='showresult'),
    path('fee',views.fee,name='fee'),
    path('calendar',views.calendar,name='calendar'),                                                            
    path('questions/',views.questions,name='questions'),                                                            
    path('datasave/',views.datasave,name='datasave'),                                                            
]

teacher/urls.py
from . import views
from django.urls import path

app_name ='teacher'

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('profile',views.profile,name='profile'),
    path('editprofile/<int:id>',views.edit_profile,name='editprofile'),
    path('courses',views.courses,name='courses'),
    path('studentlist',views.studentlist,name='studentlist'),
    path('coursewisestudentlist',views.coursewise_studentlist,name='coursewisestudentlist'),
    path('result',views.result,name='result'),
    path('calander',views.calander,name='calander'),
    path('logout',views.logout,name='logout'),
]

branch/models.py
from django.db import models
from adminapp.models import Student
# Create your models here.

class Payment(models.Model):
    student = models.ForeignKey(Student,on_delete=models.PROTECT)
    paidamount = models.IntegerField(default=0)
    paiddate = models.DateField()

    class Meta:
        db_table='payment'

student/models.py
from django.db import models
import datetime

from adminapp.models import Exam, Student,Questions

# Create your models here.

class ExamStatus(models.Model):
    # status_choices = (('Attended','Attended'),('Not Attended','Not Attended'))
    exam_id = models.ForeignKey(Exam,on_delete=models.CASCADE)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    status = models.CharField(max_length=30)
    Attended_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('exam_id', 'student')

class Answer(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE,null=True)
    exam = models.ForeignKey(Exam,on_delete=models.CASCADE,null=True)
    question = models.ForeignKey(Questions,on_delete=models.CASCADE,null=True)
    savedaswer=models.CharField(max_length=30000)
    ans_true = models.BooleanField(default=False)
    mark = models.FloatField(default=0)
    status=models.CharField(max_length=30,null=True)

branch/views.py
from django.shortcuts import render,redirect
from adminapp.models import Teacher,Student,Batch,Branch
from . models import Payment
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db.models import Sum

# Create your views here.


@login_required(login_url='/adminapp/login')
def master(request):
    details = request.user.branch
    student = Student.objects.filter(branch=request.user.branch).count()
    teacher = Teacher.objects.filter(branch=request.user.branch).count()
    branch = Branch.objects.all()
    # viewstudent = Student.objects.filter(course=id).all()

    context = {
        "is_master": True,
        "student": student,
        "teacher": teacher,
        "details": details,
        "branch": branch

    }
    return render(request, 'branch/home.html', context)

# Student listing, adding , editing,  deleting
@login_required(login_url='/adminapp/login')
def students(request):
    details = request.user.branch
    batch = Batch.objects.all()
    context = {
        "is_students": True,
        "batch": batch,
        "details": details,
        }
    return render(request, 'branch/students.html', context)


@login_required(login_url='/adminapp/login')
def studentslist(request, id):
    details = request.user.branch
    viewstudent = Student.objects.filter(course=id).all()
    context = {
        "is_studentslist": True,
        "viewstudent": viewstudent,
        "details": details,
        }
    return render(request, 'branch/students_list.html', context)


@login_required(login_url='/adminapp/login')
def all_students_list(request):
    details = request.user.branch
    student = Student.objects.filter(branch=request.user.branch)
    context = {
        "is_all_students_list": True,
        "student": student,
        "details": details,
    }
    return render(request, 'branch/allstudents_list.html', context)


@login_required(login_url='/adminapp/login')
def add_students_branch(request):
    details = request.user.branch
    studentFk = request.user.branch.id
    course = Batch.objects.all()
    if request.method == 'POST':
        name = request.POST['name']
        lastname = request.POST['lastname']
        studentid = request.POST['studentid']
        gender = request.POST['gender']
        courseid = request.POST['course']
        dob = request.POST['dob']
        phone = request.POST['phone']
        email = request.POST['email']
        password = request.POST['password']
        fathername = request.POST['fathername']
        fatherphone = request.POST['fatherphone']
        address = request.POST['address']
        studentFk = request.user.branch
        course_id = Batch.objects.get(id=courseid)
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            context = {
            "is_add_students_branch": True,
            "course": course,
            "details": details,
            "msg":"Email id Alredy Exit"
            }
            return render(request, 'branch/studentsaddbranch.html',context)
        elif Student.objects.filter(phone=phone).exists():
            context = {
            "is_add_students_branch": True,
            "course": course,
            "details": details,
            "phone":"Phone Number Alredy Exit"
            }
            return render(request, 'branch/studentsaddbranch.html',context)    
        std = Student(course=course_id, branch=studentFk, student_id=studentid, first_name=name, last_name=lastname, gender=gender,dob=dob, phone=phone, email=email, password=password, fatherphone=fatherphone, fathername=fathername, address=address)
        std.save()
        User = get_user_model()
        User.objects.create_user(email=email, password=password, Student=std)
        context = {
            "is_add_students_branch": True,
            "course": course,
            "details": details,
            "status": 1,
            }
    else:
        context = {
            "is_add_students_branch": True,
            "course": course,
            "details": details,
            "status": 0,
        }
    return render(request, 'branch/studentsaddbranch.html', context)


@login_required(login_url='/adminapp/login')
def editstudent(request, id):
    detail = request.user.branch
    editdetails = Student.objects.get(id=id)
    if request.method == 'POST':
        name = request.POST['name']
        lastname = request.POST['lastname']
        gender = request.POST['gender']
        phone = request.POST['phone']
        email = request.POST['email']
        # password = request.POST['password']
        fathername = request.POST['fathername']
        fatherphone = request.POST['fatherphone']
        #  email=email, password=password,
        Student.objects.filter(id=id).update(first_name=name,email=email, last_name=lastname, gender=gender,
                                             phone=phone, fatherphone=fatherphone, fathername=fathername)
        # Student.objects.filter(id=students_id).update(password=newpassword)
        get_user_model().objects.filter(Student = id).update(email=email)
        # changePassword.set_password(password) 
        # changePassword.save()
        return redirect('/branch/allstudentslist')
    context = {
        "is_add_students_branch": True,
        "editdetails": editdetails,
        "details": detail
        }
    return render(request, 'branch/editstudent.html', context)

def delete_student(request,id):
    Student.objects.get(id=id).delete()
    return redirect('branch:allbranchstudentslist')


# Teacher listing, adding , editing,  deleting
@login_required(login_url='/adminapp/login')
def teachers(request):
    details = request.user.branch
    techerlist = Teacher.objects.all()
    context = {
        "is_teachers": True,
        "techerlist": techerlist,
        "details": details,
    }
    return render(request, 'branch/teacherslist.html', context)


@login_required(login_url='/adminapp/login')
def add_teachers(request):
    details = request.user.branch
    course = Batch.objects.all()
    if Teacher.objects.exists():
        branch = Teacher.objects.last().id
        techer_id = 'TEC'+str(1000+branch)
    else:
        est = 0
        techer_id = 'TEC'+str(1000+est)
    if request.method == 'POST':
        name = request.POST['name']
        gender = request.POST['gender']
        Dob = request.POST['Dob']
        mobile = request.POST['mobile']
        JoiningDate = request.POST['Joining Date']
        Qualification = request.POST['Qualification']
        Experience = request.POST['Experience']
        email = request.POST['email']
        Password = request.POST['Password']
        address = request.POST['address']
        city = request.POST['city']
        state = request.POST['state']
        zipcode = request.POST['zipcode']
        country = request.POST['country']
        courseid = request.POST['course']
        techerfk = request.user.branch
        User = get_user_model()
        course_id = Batch.objects.get(id=courseid)
        if User.objects.filter(email=email).exists():
            context = {
            "is_add_students_branch": True,
            "course": course,
            "details": details,
            "msg":"Email id Alredy Exit"
            }
            return render(request, 'branch/addteacher.html',context)
        elif Teacher.objects.filter(phone=mobile).exists():
            context = {
            "is_add_students_branch": True,
            "course": course,
            "details": details,
            "phone":"Phone Number Alredy Exit"
            }
            return render(request, 'branch/addteacher.html',context)


        techer = Teacher(course=course_id, branch=techerfk, teacher_id=techer_id, Password=Password, name=name, gender=gender, dob=Dob, phone=mobile, email=email,
                         joining_date=JoiningDate, qualification=Qualification, experience=Experience, address=address, pin=zipcode, country=country, state=state, city=city)
        techer.save()
        User = get_user_model()
        User.objects.create_user(email=email, password=Password, teacher=techer)
        context = {
        "is_add_teachers": True,
        "course": course,
        "details": details,
        "status":1
    }
    else:
        context = {
        "is_add_teachers": True,
        "course": course,
        "details": details,
        "status":0
    }
    return render(request, 'branch/addteacher.html', context)


@login_required(login_url='/adminapp/login')
def editteacher(request, id):
    details = request.user.branch
    editdetails = Teacher.objects.get(id=id)
    if request.method == 'POST':
        name = request.POST['name']
        gender = request.POST['gender']
        Dob = request.POST['Dob']
        mobile = request.POST['mobile']
        JoiningDate = request.POST['Joining Date']
        Qualification = request.POST['Qualification']
        Experience = request.POST['Experience']
        email = request.POST['email']
        Password = request.POST['Password']
        address = request.POST['address']
        city = request.POST['city']
        state = request.POST['state']
        zipcode = request.POST['zipcode']
        country = request.POST['country']
        Teacher.objects.filter(id=id).update(Password=Password, name=name, gender=gender, dob=Dob, phone=mobile, email=email, joining_date=JoiningDate,qualification=Qualification, experience=Experience, address=address, pin=zipcode, country=country, state=state, city=city)
        return redirect('/branch/teacherslist')
    context = {
        "is_teachers": True,
        "details": details,
        "editdetails": editdetails,
    }
    return render(request, 'branch/editteacher.html', context)


@login_required(login_url='/adminapp/login')
def delete_teacher(request,id):

branch/templates/branch/addcourses.html
{% extends 'branch/master.html' %}
{% block content %}
{% load static %}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">
                        Add courses
                    </h3>
                    <ul class="breadcrumb">
                        <li class="">
                            <a href="{% url 'branch:master' %}">Dashboard /</a>
                        </li>
                        <li class="">
                            <a href="{% url 'branch:courses' %}">Courses /</a>
                        </li>
                        <li class="breadcrumb-item active">
                            Add Courses
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <form>
                            <div class="row">
                                <div class="col-12">
                                    <h5 class="form-title">
                                        <span>Courses Details</span>
                                    </h5>
                                </div>
                               
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>
                                            courses Name
                                        </label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>
                                            Head of courses
                                        </label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>
                                            courses Start Date
                                        </label>
                                        <input type="date" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>
                                            No of Students
                                        </label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

branch/templates/branch/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Preskool - Dashboard</title>
        <link rel="shortcut icon" href="{% static 'websites/logo.webp' %}">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">
        <link rel="stylesheet"
              href="{% static 'webapp/plugins/bootstrap/css/bootstrap.min.css' %}">
        <!-- <link rel="stylesheet"
              href="{% static 'webapp/plugins/fontawesome/css/fontawesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'webapp/plugins/fontawesome/css/all.min.css' %}"> -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">
    </head>
    <body>
        <div class="main-wrapper">
            <div class="header">
                <div class="header-left">
                    <a href="#" class="logo">
                        <img src="{% static 'websites/logo.webp' %}" alt="Logo">
                    </a>
                    <a href="#" class="logo logo-small">
                        <img src="{% static 'websites/logo.webp' %}" alt="Logo" width="30" height="30">
                    </a>
                </div>
                <a href="javascript:void(0);" id="toggle_btn">
                    <i class="fas fa-align-left"></i>
                </a>
                <a class="mobile_btn" id="mobile_btn">
                    <i class="fas fa-bars"></i>
                </a>
                <ul class="nav user-menu">
                    
                    <li class="nav-item dropdown has-arrow">
                        <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                            <span class="user-img">
                                <img class="rounded-circle"
                                     src="{% static 'default.jpg' %}"
                                     width="31"
                                     alt="Ryan Taylor">
                                     <span class="status online"></span>
                            </span>
                            <span>{{details.branch_name|upper}}</span>
                        </a>
                        <div class="dropdown-menu">
                            <div class="user-header">
                                <div class="avatar avatar-sm">
                                    <img src="{% static 'webapp/img/profiles/avatar-01.jpg' %}"
                                         alt="User Image"
                                         class="avatar-img rounded-circle">
                                </div>
                                <div class="user-text">
                                    <h6>{{details.branch_id}}</h6>
                                    <p class="text-muted mb-0">
                                        {{details.branch_name}}
                                    </p>
                                </div>
                            </div>
                            <a class="dropdown-item" href="{% url 'branch:branchprofile' %}">My Profile</a>
                            <!-- <a class="dropdown-item" href="inbox.html">Inbox</a> -->
                            <a class="dropdown-item" href="{% url 'branch:logout_view' %}">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
                    <div id="sidebar-menu" class="sidebar-menu">
                        <ul>
                            <li class="menu-title">
                                <span>Main Menu</span>
                            </li>
                            <li {% if is_master %} class="active"{% endif %}>
                                <a href="{% url 'branch:master' %}"><i class="fa fa-th"></i> <span>Dashboard</span></a>
                            </li>
                            <li {% if is_students %} class="active submenu"
                                {% elif is_studentslist %} class="active submenu"
                                {% elif is_all_students_list %} class="active submenu"
                                {% elif is_add_students_branch %} class="active submenu"
                                {% endif %}>
                                <a href="#"><i class="fas fa-user-graduate"></i> <span> Students</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li {% if is_students %} class="active"
                                    {% elif is_studentslist %} class="active" {% endif %}>
                                        <a href="{% url 'branch:branchstudents' %}">Student View</a>
                                    </li>
                                    <li {% if is_all_students_list %} class="active"{% endif %}>
                                        <a href="{% url 'branch:allbranchstudentslist' %}">Student List</a>
                                    </li>
                                    <li {% if is_add_students_branch %} class="active"{% endif %}>
                                        <a href="{% url 'branch:addstudent' %}">Student Add</a>
                                    </li>
                                </ul>
                            </li>
                            <li {% if is_teachers %} class="active submenu"
                                {% elif is_add_teachers %} class="active submenu"
                                {% endif %}>
                                <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Teachers</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li {% if is_teachers %} class="active"{% endif %}>
                                        <a href="{% url 'branch:teacherslist' %}">Teacher List</a>
                                    </li>
                                    <li {% if is_add_teachers %} class="active"{% endif %}>
                                        <a href="{% url 'branch:addteacherbranch' %}">Teacher Add</a>
                                    </li>
                                    
                                </ul>
                            </li>
                      
                            <!-- <li class="submenu">
                                <a href="#"><i class="fas fa-file-invoice-dollar"></i> <span> Accounts</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li>
                                        <a href="fees-collections.html">Fees Collection</a>
                                    </li>
                                    <li>
                                        <a href="expenses.html">Expenses</a>
                                    </li>
                                    <li>
                                        <a href="salary.html">Salary</a>
                                    </li>
                                    <li>
                                        <a href="add-fees-collection.html">Add Fees</a>
                                    </li>
                                    <li>
                                        <a href="add-expenses.html">Add Expenses</a>
                                    </li>
                                    <li>
                                        <a href="add-salary.html">Add Salary</a>
                                    </li>
                                </ul>
                            </li>
                             -->
                            <li {% if is_fees %} class="active"{% endif %}>
                                <a href="{% url 'branch:fees' %}"><i class="fas fa-comment-dollar"></i> <span>Fees</span></a>
                            </li>
                          
                            <!-- <li>
                                <a href="event.html"><i class="fas fa-calendar-day"></i> <span>Events</span></a>
                            </li> -->
                            <!-- <li>
                                <a href="time-table.html"><i class="fas fa-table"></i> <span>Time Table</span></a>
                            </li> -->
                            <!-- <li class="menu-title">
                                <span>Pages</span>
                            </li>
                            <li class="submenu">
                                <a href="#"><i class="fas fa-shield-alt"></i> <span> Authentication </span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li>
                                        <a href="login.html">Login</a>
                                    </li>
                                    <li>
                                        <a href="register.html">Register</a>
                                    </li>
                                    <li>
                                        <a href="forgot-password.html">Forgot Password</a>
                                    </li>
                                    <li>
                                        <a href="error-404.html">Error Page</a>
                                    </li>
                                </ul>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </div>
            
            {% block content %}
            {% endblock %}
        </div>
        {% block js %}
        {% endblock  %}
        <script src="{% static 'webapp/js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/apexchart/apexcharts.min.js' %}"></script>
        <script src="{% static 'webapp/plugins/apexchart/chart-data.js' %}"></script>
        <script src="{% static 'webapp/js/script.js' %}"></script>
         
    </body>
</html>